### ISSUE TITLE
Tests fail (with older Calendar::Japanese::Holiday?)

### ISSUE THREAD

**Issue by eserte** [worthmine/Date-Cutoff-JP#1]
On some of my smokers the test suite fails:
```
#   Failed test 'payday for Mar.'
#   at t/01_basic.t line 19.
#          got: '2019-04-30'
#     expected: '2019-05-07'

#   Failed test 'cutoff for Apr.'
#   at t/01_basic.t line 22.
#          got: '2019-04-30'
#     expected: '2019-05-07'
# Looks like you failed 2 tests of 24.
t/01_basic.t ....................... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/24 subtests 
... etc ...
```

This seems to happen if an older version of Calendar::Japanese::Holiday is installed, that is, for versions less than 0.05.

**Comment by worthmine** [comment]
thanks for reporting.

Yes, it depends on latest Calendar::Japanese::Holiday. so I've changed cpanfile just now.
If travis passes, I will bump the version 0.04 to 0.05

**Comment by worthmine** [comment]
Done. Do you reproduce it?

**Comment by eserte** [comment]
The latest release looks fine.
